version: "3.9"
services:
  forum:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ADDR=:8080
      - SQLITE_DSN=file:/app/data/forum.db?_foreign_keys=on
    volumes:
      - forum_data:/app/data
volumes:
  forum_data: {}